### ISSUE TITLE
Implement DataFrame.items

### ISSUE THREAD

**Issue by toxicafunk** [SciScala/SimpleDF#3]
Implement `DataFrame.items(df: DFImpl)` according to [pandas.DataFrame.items](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.items.html) such that:

```scala
for ((label,content) <- df.items()) {
  ...
}
```

**Comment by hg1112** [comment]
I have picked this function to start with. And have already implemented it.
How to start a PR from here ?

**Comment by toxicafunk** [comment]
Go to the main repo, SciScala/SimpleDF then to the PR tab and add a PR.
Then just choose your repo and your branch.

**Comment by hg1112** [comment]
Please link my pull request https://github.com/SciScala/SimpleDF/pull/9 to this issue

**Comment by toxicafunk** [comment]
Implemented in #9
